name: healthmed-ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore HealthMed/HealthMed.Api.csproj

    - name: Build
      run: dotnet build HealthMed/HealthMed.Api.csproj --configuration Release --no-restore

    - name: Test
      run: dotnet test HealthMed/HealthMed.Api.csproj --configuration Release